name: Continuous Integration

on:
  push:
    branches: [ main, develop, 'feature/*' ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 2 * * 1' # Weekly dependency check
  workflow_dispatch:

env:
  JAVA_VERSION: '21'
  MILL_VERSION: '1.0.1'

jobs:
  validate:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better blame info

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Ensure Mill Script is Executable
        run: chmod +x ./mill

      - name: Cache Mill & Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/mill
            ~/.ivy2/cache
            ~/.m2/repository
          key: ${{ runner.os }}-mill-${{ hashFiles('build.sc') }}
          restore-keys: |
            ${{ runner.os }}-mill-

      - name: Validate Formatting
        run: ./mill mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll

      - name: Compile All Modules
        run: |
          ./mill valmuri.compile
          ./mill cli.compile
          ./mill examples.helloWorld.compile

      - name: Run Unit Tests
        run: ./mill testAll

      - name: Generate Coverage Report
        run: ./mill coverage

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./out/valmuri/scoverage/htmlReport.dest/scoverage.xml
          fail_ci_if_error: true

      - name: Run Integration Tests
        run: |
          ./mill examples.helloWorld.run &
          APP_PID=$!
          sleep 10
          curl -f http://localhost:8080/health || exit 1
          kill $APP_PID

      - name: Scan for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Security Report
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  test-cross-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Ensure Mill Script Executable
        run: chmod +x ./mill
      - name: Run Tests
        run: ./mill testAll

  performance-benchmark:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Ensure Mill Script Executable
        run: chmod +x ./mill
      - name: Run Benchmarks
        run: ./mill benchmarks.runMain org.openjdk.jmh.Main
      - name: Upload Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'jmh'
          output-file-path: benchmark-results.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [validate, test-cross-platform]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Ensure Mill Script Executable
        run: chmod +x ./mill
      - name: Publish Modules
        run: ./mill mill.scalalib.PublishModule/publishAll
      - name: Build CLI Bundle
        run: ./mill cli.assembly
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/cli/assembly.dest/out.jar
          generate_release_notes: true
