name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    name: Run scala tests
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        scala: [ 2.13.12 ]
        java: [ 21 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'sbt'
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Check code formatting
        run: sbt scalafmtCheckAll

      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: sbt clean +test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.os }}-scala-${{ matrix.scala }}-java-${{ matrix.java }}
          path: |
            **/target/test-reports/
            **/target/scala-${{ matrix.scala }}/test-reports/
          retention-days: 5
