name: Run tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    if: false  # Disable this job by default, enable specific jobs below
    name: Run scala tests
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        scala: [ 2.13.12 ]
        java: [ 21 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'sbt'
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1

      - name: Cache sbt/ivy2 and coursier
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: sbt-cache-${{ runner.os }}-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            sbt-cache-${{ runner.os }}-

      - name: Update dependencies
        run: sbt update

      - name: Check code formatting
        run: sbt scalafmtCheckAll

      - name: Run tests
        run: sbt clean +test

      - name: Run DI/Config tests
        run: sbt "testOnly *config* *di*"

      - name: Test configuration loading
        run: |
          echo "VALMURI_ENV=test" >> $GITHUB_ENV
          sbt "testOnly valmuri.test.config.*"

      - name: Validate example app with DI
        run: sbt "helloWorld/run &" && sleep 5 && curl http://localhost:8080/health

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-scala-${{ matrix.scala }}-java-${{ matrix.java }}
          path: |
            **/target/test-reports/
            **/target/scala-${{ matrix.scala }}/test-reports/
          retention-days: 14
